@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name":"Hakuna Matata",
  "email":"hakuna@matata.dev",
  "password":"password"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email":"hakuna@matata.dev",
  "password":"password"
}

###

# @name create_question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title":"Terceira pergunta",
  "content":"Quem é o cachorro mais lindo do mundo?"
}

###

# @name fetch_recente_questions
GET {{baseUrl}}/questions?page=2
Content-Type: application/json
Authorization: Bearer {{authToken}}

